### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by Loryhoof** [tomo0613/offroadJS#1]
I'm sorry for posting an issue, but I don't have any other way to contact you :/

Could you give me tips on how use a heightmap generated in threejs, and use that for the cannonjs heightfield?
Like, take the heightmap data and convert (?) it into a heightfield matrix, it seems I cant just plug the same heightmap values into the Cannon shape.

I really like this project, I'm making my own gta-style game with Threejs and CannonJS right now.

**Comment by tomo0613** [comment]
check this issue: (my last comment)
https://github.com/schteppe/cannon.js/issues/434
I'm sure there is a better solution, if you found something interesting you can comment it here or there.

this maybe can help if you have not seen it:
 https://github.com/swift502/Sketchbook

**Comment by Loryhoof** [comment]
I kinda figured it out, I used your MeshToHeightfield function, but I noticed that you have to be careful with scaling the terrain inside Blender, it only works if you scale the individual selected faces (in Edit mode), but not if you scale the mesh in Object mode, it will console.log a size of 2 - 2, even if you scale it 1000x.

About the second link, my project is actually based on Sketchbook :) 
Its called CrookTown https://www.youtube.com/channel/UC2tbysPFyHPFrp5a_uWupgw/videos

I linked your repo in the Sketchbook discord, hopefully it can help someone

**Comment by Loryhoof** [comment]
I made a Heightfield generator based on offroadJS, theres still a bunch of problems but you can just upload a glb and it will generate it, without having to mess with the code. 
https://github.com/Loryhoof/Mesh2Heightfield

**Comment by SergueyML** [comment]
You can fix the scale issue by creating a new THREE.Box3 and setting it from the mesh. The geometry in the mesh does not apply the scale vector for some reason.
```
  const box = new THREE.Box3();
  box.setFromObject( mesh );
 ```

**Comment by serge1165** [comment]
You can fix the scale issue by creating a new THREE.Box3 and setting it from the mesh. The geometry in the mesh does not apply the scale vector for some reason.
```
  const box = new THREE.Box3();
  box.setFromObject( mesh );
```

**Comment by karasuuuuu** [comment]
> I made a Heightfield generator based on offroadJS, theres still a bunch of problems but you can just upload a glb and it will generate it, without having to mess with the code. https://github.com/Loryhoof/Mesh2Heightfield

Hey can you help me with the cannon part of the wheightfield? I have the example mesh you used in place, but when I add the cannon invisible collider mesh it doesnt seem t o line up. Your heightfield generator only works when Y-up is disabled. How do I get the cannon HF to line up with the visible one? is it something to do with scale or rotation?

**Comment by serge1165** [comment]
If you scale/rotate your mesh from which you want to create the HF from in a 3D software lime Blender, you have to apply those changes.   CannonJS does not take scale in to account.

**Comment by karasuuuuu** [comment]
> If you scale/rotate your mesh from which you want to create the HF from in a 3D software lime Blender, you have to apply those changes. CannonJS does not take scale in to account.

Hey thanks for the reply, I know I can rotate in blender, I would hope to just use the same coordinates, but it doesnt seem to line up. In order to get the array I need to use loryhoof's generator, but it wont work unless y-up is disabled, which means the points are rotated I think. Is there another way to even get a cannon hf, or to get it lined  up?

**Comment by serge1165** [comment]
> > If you scale/rotate your mesh from which you want to create the HF from in a 3D software lime Blender, you have to apply those changes. CannonJS does not take scale in to account.
> 
> Hey thanks for the reply, I know I can rotate in blender, I would hope to just use the same coordinates, but it doesnt seem to line up. In order to get the array I need to use loryhoof's generator, but it wont work unless y-up is disabled, which means the points are rotated I think. Is there another way to even get a cannon hf, or to get it lined up?

Weird, it worked for me whenever I used it. Did you by any chance move the original mesh before running the HF code? Can you try making a completely new 3d model without scaling and see if that works with y-up?

**Comment by karasuuuuu** [comment]
Ill try to mess with it some more, Im just using the sample height field he provided, trying to apply it to tomo's off road thing.

**Comment by tomo0613** [comment]
If you still struggling I suggest give this https://github.com/schteppe/cannon.js/issues/434#issuecomment-733781546 a try

**Comment by karasuuuuu** [comment]
> If you still struggling I suggest give this [schteppe/cannon.js#434 (comment)](https://github.com/schteppe/cannon.js/issues/434#issuecomment-733781546) a try

Hi @tomo0613  thanks for replying! Im not sure how I would use that code, Im still a beginner with three/cannon. How do I feed themesh to generate the array? (by the way, I played offroad and got like 75% of th eway pu that mountain. That game is brutal lol. Did you actually complete it?
 
> Weird, it worked for me whenever I used it. Did you by any chance move the original mesh before running the HF code? Can you try making a completely new 3d model without scaling and see if that works with y-up?

@SergueyPutilin Im super close to getting it working, I use the ruler tool to measure the point distance, but meshtoheightfield seems to only give me a small fraction of the whole array, so the hf is just about 10 polys but my mesh must be in the 1000s. Im pretty sure all the points are above 0 in Z. Appreciate any ideas!

**Comment by tomo0613** [comment]
@karasuuuuu 
> how I would use that code

So based on [my code](https://github.com/tomo0613/offroadJS/blob/0987514fb7c34b3aff2ac6a4dd9c513ec8f6e6e4/client/main.js) I would call that method right after loading the mesh.
[this file](https://github.com/tomo0613/offroadJS/blob/0987514fb7c34b3aff2ac6a4dd9c513ec8f6e6e4/client/terrainHeightMap.js) contains the data, that is generated by the `generateHeightfieldFromMesh` method

here's an example:
```
(async function init() {
    ...

    const [terrainGLB] = await Promise.all([
        utils.loadResource('model/terrain.glb'),
    ]);

    const terrain = terrainGLB.scene;

    /*
      "generateHeightfieldFromMesh" can take some time to finish, but you don't want to call it every time you start the app
      when you satisfied with the result, copy paste the data from the console to a .js file and import it from there,
      instead of calling "generateHeightfieldFromMesh" (remove the 3 lines below, and 1 new that imports heightFieldData )
    */
    const pointDistance = 1.4; // tweak this value to fit your mesh    
    const heightFieldData = await generateHeightfieldFromMesh(terrain, pointDistance);
    console.log(heightFieldData);

    const terrainShape = new CANNON.Heightfield(heightFieldData.heightMap, { elementSize: heightFieldData.pointDistance });
    const heightfield = new CANNON.Body({ mass: 0, shape: terrainShape });
    heightfield.quaternion.setFromAxisAngle(new CANNON.Vec3(1, 0, 0), -Math.PI / 2);
    heightfield.position.set(heightFieldData.minX, 0, heightFieldData.maxZ);

    gScene.add(terrain);
    gWorld.addBody(heightField);
    ...
})();

...

async function generateHeightfieldFromMesh(mesh, pointDistance) {
    const rayCaster = new THREE.Raycaster();
    const rayCasterPosition = new THREE.Vector3();
    const upAxis = new THREE.Vector3(0, 1, 0);

    const heightMap = [];

    const geometry = findGeometry(mesh);
    geometry.computeBoundingBox();
    const {
        min: {x: minX, y: minY, z: minZ},
        max: {x: maxX, z: maxZ},
    } = geometry.boundingBox;

    const width = maxX - minX;
    const length = maxZ - minZ;
    const totalX = width / pointDistance + 1;
    const totalZ = length / pointDistance + 1;
    const totalSteps = totalX * totalZ;
    let currentStep = 0;

    for (let x = minX; x <= maxX; x += pointDistance) {
        const heightDataRow = [];
        heightMap.push(heightDataRow);

        for (let z = maxZ; z >= minZ; z -= pointDistance) {
            rayCasterPosition.set(x, minY, z);
            rayCaster.set(rayCasterPosition, upAxis);

            const y = await calculateMeshSurfaceDistanceByRayCast();

            heightDataRow.push(y);
        }
    }

    const result = {
        pointDistance,
        position: [minX, 0, maxZ],
        heightMap,
    };

    return result;
    
    function calculateMeshSurfaceDistanceByRayCast() {
        return new Promise((resolve) => {
            window.setTimeout(() => {
                currentStep++;

                console.log(`generating height field... ${Math.floor(100 / totalSteps * currentStep)}%`);

                const [result] = rayCaster.intersectObject(mesh, true);

                resolve(result.distance);
            });
        });
    }
}
```

(no I couldn't reach the top :) , have you tried this one https://github.com/tomo0613/offroadJS_v2 ? I think it's more challenging)

**Comment by karasuuuuu** [comment]
So it will generate the array automatically? But if I simply replace the GLB file it keep the old heightfield I think, So Im obviously missing a step.

Yes I played it- its so hard, but more challenging than IMPOSSIBLE? Im not sure lol. That version is typescript, so one thing at a time. I want to understand JS version first!

**Comment by karasuuuuu** [comment]
Hey its me again. Ive slowly been progressing on a small project and Ive been learning a lot from this base! I have a question about how you load the GLTF models, you dont use a gltf loader, so how can I add shadows to my modells or cast shadows? As you are using some array method.
In a regular gltf I might add

`gltf.scene.traverse( function( node ) {

    if ( node.isMesh ) { node.castShadow = true; }

} );`

but not sure where to add with your method.
