### ISSUE TITLE
@karasuuuuu

### ISSUE THREAD

**Issue by karasuuuuu** [tomo0613/offroadJS#2]
Hey its me again. Ive slowly been progressing on a small project and Ive been learning a lot from this base! I have a question about how you load the GLTF models, you dont use a gltf loader, so how can I add shadows to my modells or cast shadows? As you are using some array method. 
In a regular gltf I might add  

`gltf.scene.traverse( function( node ) {

        if ( node.isMesh ) { node.castShadow = true; }

    } );`

but not sure where to add with your method.

**Comment by tomo0613** [comment]
@karasuuuuu 
`utils.loadResource()` just wraps `GLTFLoader` in a `Promise`
the idea behind, to be able to load the models parallel
```
const [wheelGLTF, chassisGLTF, terrainGLB] = await Promise.all([
        utils.loadResource('model/lowPoly_car_wheel.gltf'),
        utils.loadResource('model/mg.gltf'),
        utils.loadResource('model/terrain.glb'),
]);
```

`const chassis = chassisGLTF.scene;` 
here you can use the regular traverse method
```
chassis.traverse((node) => {
    ...
})
```
same for `terrain` if u need to set `receiveShadows`
